### PR TITLE
Bump Version

### PR DESCRIPTION
**Pull request by mathewmeconry**
Bumps the version to 5.5.1
pom.xml and readme updated (including the install command)

Tests were local successful and it works in my test environment

### CODE REVIEW

**Comment by jalaziz** [comment]
@jlinn Just a bump on getting this merged! Our cluster upgrade is blocked on this :(

**Comment by mathewmeconry** [comment]
@jalaziz You can use the release inn my fork. There is a compiled version with the version bump

**Comment by jalaziz** [comment]
@mathewmeconry I'd love to, but we're using a hosted provider and they're requesting that the plugin be updated on the original repo 😞

**Comment by jlinn** [comment]
Thanks for the update!

**Comment by jlinn** [comment]
[v5.5.1.0](https://github.com/jlinn/elasticsearch-analysis-url/releases/tag/v5.5.1.0) has been released. Apologies for the delay.

**Pull request merged**
